### ISSUE TITLE
登录不了

### ISSUE THREAD

**Issue by Wolfdebug** [youngle316/chatgpt-nextjs#58]
我按照你的步骤一步步来的，登录总是超时
![image](https://user-images.githubusercontent.com/26107190/233817037-81e941ee-a1af-4d6a-a900-c7b973057fe3.png)
```bash
 providerId: 'google',
 message: 'outgoing request timed out after 3500ms'
```
开代理也不行，可以确认我的代理是没问题的，可以上gpt官网使用

**Comment by youngle316** [comment]
本地登录有问题，推荐代理工具使用 [Clash for Windows](https://github.com/Fndroid/clash_for_windows_pkg/releases) 开启 TUN 模式
<img width="157" alt="image" src="https://user-images.githubusercontent.com/38031149/233880625-a219241a-7f73-4b41-8ac6-0631ae626c7b.png">
